// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtUqYjNUhdiR07rck4VEQmO39zHAsCtBk',
    appId: '1:321182641847:web:f1e784a2634010c8c3a732',
    messagingSenderId: '321182641847',
    projectId: 'split-wise-app-dev',
    authDomain: 'split-wise-app-dev.firebaseapp.com',
    storageBucket: 'split-wise-app-dev.firebasestorage.app',
    measurementId: 'G-KSV5WC9PJR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGZsWwEQFHIXFmfuFnSb4FSVv3gtt02Qo',
    appId: '1:321182641847:android:4a798bdedacdec6ac3a732',
    messagingSenderId: '321182641847',
    projectId: 'split-wise-app-dev',
    storageBucket: 'split-wise-app-dev.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAr0__t-D8tTfjldCDruWp4S991e0EoNME',
    appId: '1:321182641847:ios:e4e32d629480468bc3a732',
    messagingSenderId: '321182641847',
    projectId: 'split-wise-app-dev',
    storageBucket: 'split-wise-app-dev.firebasestorage.app',
    iosBundleId: 'com.startup.splitWise',
  );
}
